---
title: "Interaktioner og modelspecifikation"
subtitle: |
  | Metode 3
  | [.white[Link til slides: kortlink.dk/2acdr]](https://soerendamsbo.github.io/m3/m3-2_interaktion-modelspecifikation.html)
author: Søren Damsbo-Svendsen<br>[.white[sdas@ifs.ku.dk]](mailto:sdas@ifs.ku.dk)
institute: Institut for Statskundskab<br>Københavns Universitet
date: "Uge 9"
output:
  xaringan::moon_reader:
    css: "style.css"
    self_contained: true
    nature:
      ratio: '16:9'
      highlightStyle: github
      highlightLines: true
      countincrementalSlides: false
---
class: center, middle

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=T, warnings=F, message=F)
pacman::p_load(Statamarkdown)
```

# Spørgsmål 1

I skal undersøge om urbanisering (urban - procent andel af mennesker, der bor i byområder) har en indflydelse på antallet af restriktioner af lovlig abort (abortlaw2017), når der kontrolleres for befolkningens gennemsnitlige støtte til homoseksuelle rettigheder (gay_support) og hvorvidt det er en sydlig stat ’Southern State’ (south). Før I gør det, skal I reflektere hvad jeres analyseenhed er og undersøge variablenes måleniveau (fx med codebook). Fortolk regressionsresultatet af modellen.

---

```{stata, echo=1, cleanlog=FALSE} 
webuse auto
tostring headroom, generate(ny)
encode ny, generate(ny2)
reg price c.mpg##i.ny2
margins, dydx(mpg) over(ny2)
marginsplot
graph export "test.png", replace
```

```{stata} 

use "/Users/soren/OneDrive - Københavns Universitet/Teaching/metode3/øvelsesopgaver/Data/states.dta", clear
codebook abortlaw2017 urban gay_support south, compact

```

---

```{stata, echo=1, cleanlog=FALSE} 

use "/Users/soren/OneDrive - Københavns Universitet/Teaching/metode3/øvelsesopgaver/Data/states.dta", clear
regress c.abortlaw2017 c.urban c.gay_support i.south

```

---
class: center, middle
  
# Spørgsmål 2

Undersøg dernæst vha. en interaktionsmodel om stemmeandelen til Trump i 2016 (trump16) modererer effekten af urbanisering i modellen fra opgave 4.1. Husk at der enten skal stå i. eller c. foran de variable som interageres. Fortolk resultatet. Illustrér interaktionen mellem Trump-stemmeandel og urbanisering vha. marginale effekter (jf. Sønderskov afsnit 10.1.17).

---
class: center, middle

# Spørgsmål 3

Sønderskov (2014) kommenterer, at der i modeller med interaktion ofte vil være multikollinearitet. Diskutér, hvorfor det er tilfældet og undersøg, hvorvidt det også gælder i modellen 4.2. Derudover anbefaler Sønderskov at anvende robuste standardfejl i modeller med interaktionsled. Ændrer der på resultaterne i ovenstående [4.2]?

---
class: center, middle

# Spørgsmål 4

Undersøg dernæst, om der er forskel i effekten af befolkningens gennemsnitlige støtte til homoseksuelle rettigheder (gay_support) mellem Sydstaterne og andre stater. Lav en interaktionsmodel med interaktion mellem gay_support og south. Fortolk resultatet.

---
class: center, middle

# Spørgsmål 5

Undersøg dernæst, om der er forskel i effekten af tidsbegrænsninger for lovgiver mellem Sydstaterne og andrestater. Lav en interaktionsmodel med interaktion mellem term_limits og south. Fortolk resultatet og illustrér interaktionen vha. marginale effekter.

---
class: center, middle

# Spørgsmål 6

Undersøg dernæst, om der er forskel i effekten af urbanisering mellem graden af sekularisme (secularism3). Lav en interaktionsmodel med interaktion mellem urban og secularism3. Fortolk resultatet.

---
class: center, middle

# Spørgsmål 7

Diskuter i hvilken grad de forskellige kriterierne for kausalitet er overholdt i disse analyser.